/* USER */
export const LOGIN_USER = "LOGIN_USER";

/* JOBS */
export const RECIEVE_JOBS = "RECIEVE_JOBS";
export const FETCH_JOBS = "FETCH_JOBS";

/* ORGANIZATIONS */
export const UNIQUE_ORGANIZATIONS = "UNIQUE_ORGANIZATIONS";
export const ADD_SELECTED_ORGANIZATIONS = "ADD_SELECTED_ORGANIZATIONS";
export const FILTERED_JOBS_BY_ORGANIZATIONS = "FILTERED_JOBS_BY_ORGANIZATIONS";
export const SELECTED_ORGANIZATIONS = "SELECTED_ORGANIZATIONS";
